### PR TITLE
Bump parent pom from 6.2.0 to 6.7.0

### PR DESCRIPTION
**Pull request by alecharp**
In order to validate the plugin with Jetty 12, we need to get https://github.com/jenkinsci/plugin-pom/pull/693 which is included in `4.62` version. That bump occurred on the `analysis-pom` version `6.7.0`.

### Testing done

None. Relying on the CI to build this.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by uhafner** [comment]
The plugin is deprecated and not used anymore. Wouldn't it make more sense to remove it from the tests?

**Comment by alecharp** [comment]
I agree it would however, this is not something I can achieve as quickly as I would like to. And in the mean time, this would kinda resolve the problem I see in my Jetty 12 testing.

**Comment by uhafner** [comment]
Do you need a release as well?

**Comment by alecharp** [comment]
Yes that would be perfect if you could release this. Thank you @uhafner for your help on this.

**Pull request merged**
